version: '3.9'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - db-connect
    ports:
      - ${DB_PORT}:5432

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./api/src:/api/src
      - ./api/node_modules:/api/node_modules
    depends_on:
      - db
    networks:
      - db-connect
      - webapp
    ports:
      - ${API_PORT}:3000
    env_file: .env
    environment:
      - NODE_ENV=production

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    networks:
      - webapp
    ports:
      - 80:80
    restart: always
    container_name: web
    env_file:
      - .env
    environment:
      - REACT_APP_NODE_ENV=production

volumes:
  postgres-data:

networks:
  db-connect:
    driver: bridge
  webapp:
    driver: bridge
